// react-calendar/src/components/calendar/calendarTable/CalendarTable.jsx
import React from 'react';
import {connect} from "react-redux";
import './table.css';
import '../../messages/messages.css';
import '../../../scss/buttonTransition.css';
import {callMsGraphApi} from "../../../store/graph/graphReducer";
import CalendarItem from "./CalendarItem";
import Loader from "../../loader/Loader";
import {CSSTransition, TransitionGroup} from "react-transition-group";
import InfoMessage from "../../messages/InfoMessage";
import TableHead from "./TableHead";
import TableBody from "./TableBody";

class CalendarTable extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            events: [],
            eventIds: [],
            loading: false,
            loadError: ''
        }
    }

    async componentDidMount() {
        const queryFields = ['subject', 'bodyPreview', 'attendees', 'organizer', 'location', 'start', 'end'];

        const queryOptions = {
            path: '/me/events',
            selectedParams: queryFields.join(),
            orderByParams: 'createdDateTime DESC'
        };
        try {
            this.setState({loading: true});
            await this.props.callMsGraphApi(queryOptions)
                .then(resp => {
                    this.setState({events: resp.value});
                });
        } catch (e) {
            this.setState({loadError: e.message});
        } finally {
            this.setState({loading: false});
        }
    }

    deleteChosenEvents = async () => {
        let arr = this.state.events;
        for (let i = 0; i < this.state.eventIds.length; i++) {
            const eventId = this.state.eventIds[i];
            await this.props.graphClient.api(`/me/events/${eventId}`).delete();
            arr = arr.filter(event => event.id !== eventId);
        }
        this.setState({eventIds: []});
        this.setState({events: arr});
    };

    popDeletedId = eventId => this.setState({eventIds: this.state.eventIds.filter(id => id !== eventId)});
    saveDeletedId = eventId => {
        if (!this.state.eventIds.includes(eventId)) {
            this.setState({eventIds: [...this.state.eventIds, eventId]});
        }
    };

    render() {
        if (this.state.loading) {
            return <Loader/>;
        } else if (this.state.events.length) {
            return <>
                <table>
                    <TableHead/>
                    <TableBody events={this.state.events}
                               popDeletedId={this.popDeletedId}
                               saveDeletedId={this.saveDeletedId}
                    />
                </table>
                <TransitionGroup>
                    {
                        this.state.eventIds.length
                        &&
                        <CSSTransition timeout={1000} classNames={'button'} mountOnEnter unmountOnExit>
                            <div>
                                <button className={'btn btn-danger mt-2'}
                                        onClick={() => this.deleteChosenEvents()}
                                >
                                    Delete selected elements
                                </button>
                            </div>
                        </CSSTransition>
                    }
                </TransitionGroup>
            </>
        } else if (this.state.loadError.length) {
            return <InfoMessage className={'alert-message'}>{this.state.loadError}</InfoMessage>
        } else {
            return <InfoMessage className={'info-message'}>No events!</InfoMessage>;
        }
    }
}

const mapStateToProps = state => ({
    graphClient: state.graphReducer.graphClient
})

const mapDispatchToProps = {
    callMsGraphApi
}

export default connect(mapStateToProps, mapDispatchToProps)(CalendarTable);

// vue_calendar/src/components/user_components/calendar/CalendarTable.vue
<template>
  <div>
    <Loader v-if="loading"/>
    <div v-else-if="events.length">
      <table>
        <tr>
          <th scope="col"></th>
          <th scope="col">Subject</th>
          <th scope="col">Body</th>
          <th scope="col">Organizer</th>
          <th scope="col">Location</th>
          <th scope="col">Start</th>
        </tr>
        <CalendarItem v-for="event in events" :key="event.id" :event="event" @push-deleted-event-id="saveDeletedId"
                      @pop-deleted-event-id="popDeletedId"/>
      </table>
      <transition name="fade">
        <b-button v-if="eventIds.length" variant="danger" @click="deleteChosenEvents" class="my-2">
          Delete selected elements
        </b-button>
      </transition>
    </div>
    <div v-else>No events!</div>
  </div>
</template>

<script>
import {mapActions, mapGetters} from "vuex";
import CalendarItem from "@/components/user_components/calendar/CalendarItem";
import Loader from "@/components/Loader";

export default {
  name: "CalendarTable",
  components: {CalendarItem, Loader},
  data() {
    return {
      events: [],
      fields: ['subject', 'bodyPreview', 'attendees', 'organizer', 'location', 'start', 'end'],
      loading: true,
      eventIds: []
    }
  },
  computed: {...mapGetters(["getGraphClient"])},
  methods: {
    ...mapActions(["callMsGraphApi"]),
    saveDeletedId(eventId) {
      if (!this.eventIds.includes(eventId)) {
        this.eventIds.push(eventId);
      }
    },
    popDeletedId(eventId) {
      this.eventIds = this.eventIds.filter(id => id !== eventId);
    },
    deleteChosenEvents() {
      for (let i = 0; i < this.eventIds.length; i++) {
        this.getGraphClient.api(`/me/events/${this.eventIds[i]}`).delete();
        this.events = this.events.filter(event => event.id !== this.eventIds[i]);
      }
      this.eventIds = [];
    },
    getEvents() {
      const queryOptions = {
        path: '/me/events',
        selectedParams: this.fields.join(),
        orderByParams: 'createdDateTime DESC'
      };
      this.callMsGraphApi(queryOptions).then(resp => {
        this.events = resp.value;
        this.loading = false;
      }).catch(err => console.log(err));
    }
  },
  async mounted() {
    this.getEvents();
    this.$parent.$on('updateEventsTable', this.getEvents);
  }
}
</script>

<style scoped lang="scss">
table {
  border          : $border;
  border-collapse : collapse;

  tr {
    vertical-align : top;

    &:nth-child(even) {
      background-color : antiquewhite;
    }

    &:hover:nth-child(n+2) {
      background-color : #deeef3;
    }
  }

  th {
    border  : $border;
    padding : $indent;
  }
}
</style>
