// react-calendar/src/components/calendar/CalendarItem.jsx
import React from 'react';
import {Form} from 'react-bootstrap';
import './table.css';
import moment from "moment";

const CalendarItem = ({event}) => {
    const checkForEmpty = value => value === '' ? '-' : value;
    const dateFormatter = value => moment(value).format('DD.MM.YYYY HH:mm');
    const trimLongString = value => {
        const MIN_DISPLAYED_LENGTH = 20;
        return value.length >= MIN_DISPLAYED_LENGTH ? value.slice(0, MIN_DISPLAYED_LENGTH).trim() + "..." : value;
    };
    return (
        <tr>
            <td>
                <Form.Check type={'checkbox'}/>
            </td>
            <td title={event.subject}>
                {trimLongString(event.subject)}
            </td>
            <td title={event.bodyPreview}>
                {trimLongString(checkForEmpty(event.bodyPreview))}
            </td>
            <td title={event.organizer.emailAddress.name}>
                {trimLongString(event.organizer.emailAddress.name)}
            </td>
            <td title={event.location.displayName}>
                {trimLongString(checkForEmpty(event.location.displayName))}
            </td>
            <td title={event.start.dateTime}>
                {dateFormatter(event.start.dateTime)}
            </td>
        </tr>
    );
};

export default CalendarItem;

// vue_calendar/src/components/user_components/CalendarItem.vue
<template>
  <tr>
    <td>
      {{ event.subject }}
    </td>
    <td>
      {{ event.bodyPreview }}
    </td>
    <td>
      {{ event.attendees | stylizeAttendees }}
    </td>
    <td>
      {{ event.organizer.emailAddress.name }}
    </td>
    <td>
      {{ event.start.dateTime | moment('DD.MM.YYYY HH:mm Z') }}
    </td>
    <td>
      {{ event.end.dateTime | moment('DD.MM.YYYY HH:mm Z') }}
    </td>
  </tr>
</template>

<script>
export default {
  name: "CalendarItem",
  props: {
    event: {
      type: Object,
      required: true
    }
  },
  filters: {
    stylizeAttendees: value => {
      console.log(value.length)
      if (value.length) {
        return '-';
      } else {
        // return value.emailAddress.address;
        return '---';
      }
    }
  }
}
</script>

<style scoped lang="scss">
td {
  border  : $border;
  padding : $indent;
}
</style>
