// vue_calendar/src/components/user_components/calendar/CalendarItem.vue
<template>
  <tr>
    <td>
      <b-form-checkbox class="checkbox" :id="`checkbox-${event.id}`" v-model="status" :name="`checkbox-${event.id}`"
                       value="accepted" unchecked-value="not_accepted" @change="processEventId"/>
    </td>
    <td v-b-modal="`event-${event.id}-details`" :title="event.subject">{{ event.subject | trimLongString }}</td>
    <td v-b-modal="`event-${event.id}-details`" :title="event.bodyPreview">
      {{ event.bodyPreview | trimLongString | checkForEmpty }}
    </td>
    <td v-b-modal="`event-${event.id}-details`">{{ event.organizer.emailAddress.name }}</td>
    <td v-b-modal="`event-${event.id}-details`">{{ event.location.displayName | checkForEmpty }}</td>
    <td v-b-modal="`event-${event.id}-details`">{{ event.start.dateTime | dateFormatter }}</td>

    <b-modal :id="`event-${event.id}-details`" hide-footer>
      <template #modal-title>Event info</template>
      <EventsDetail :event="event"/>
      <b-button variant="danger" class="m-3" @click="$bvModal.hide(`event-${event.id}-details`)">Close</b-button>
    </b-modal>
  </tr>
</template>

<script>
import EventsDetail from "@/components/user_components/calendar/form/EventsDetail";

export default {
  name: "CalendarItem",
  components: {EventsDetail},
  data() {
    return {
      status: 'not_accepted'
    }
  },
  props: {
    event: {
      type: Object,
      required: true
    }
  },
  filters: {
    trimLongString(value) {
      const minDisplayedLength = 20;
      return value.length >= minDisplayedLength ? value.slice(0, minDisplayedLength).trim() + "..." : value;
    }
  },
  methods: {
    processEventId() {
      if (this.status === 'accepted') {
        this.$emit('push-deleted-event-id', this.event.id);
      }
      if (this.status === 'not_accepted') {
        this.$emit('pop-deleted-event-id', this.event.id);
      }
    }
  }
}
</script>

<style scoped lang="scss">
td {
  border    : $border;
  padding   : $indent;
  cursor    : pointer;
  min-width : 200px;

  &:nth-child(1) {
    min-width : 1.5em;
  }
}

.checkbox {
  margin-left : $indent;
}
</style>

// react-calendar/src/components/calendar/calendarTable/CalendarItem.jsx
import React, {useState} from 'react';
import {Form} from 'react-bootstrap';
import './table.css';
import EventsDetail from "../modal/EventsDetail";
import {checkForEmpty, dateFormatter, trimLongString} from "../filters";

const CalendarItem = ({event, saveEventId, popEventId}) => {
    const [modal, setModal] = useState(false);

    const processEventId = (e) => {
        if (e.target.checked) {
            saveEventId(event.id);
        } else {
            popEventId(event.id);
        }
    };

    return (
        <>
            <tr onClick={() => setModal(true)}>
                <td>
                    <Form.Check type={'checkbox'}
                                className={'checkbox'}
                                onChange={(e) => processEventId(e)}
                    />
                </td>
                <td title={event.subject}>
                    {trimLongString(event.subject)}
                </td>
                <td title={event.bodyPreview}>
                    {trimLongString(checkForEmpty(event.bodyPreview))}
                </td>
                <td title={event.organizer.emailAddress.name}>
                    {trimLongString(event.organizer.emailAddress.name)}
                </td>
                <td title={event.location.displayName}>
                    {trimLongString(checkForEmpty(event.location.displayName))}
                </td>
                <td>
                    {dateFormatter(event.start.dateTime)}
                </td>
            </tr>
            <EventsDetail visible={modal} setVisible={setModal} event={event}/>
        </>
    );
};

export default CalendarItem;
