// vue_calendar/src/components/user_components/calendar/form/EventsDetail.vue
<template>
  <div>
    <EventsDetailField :field-name="'Subject:'" :field-data="event.subject"/>
    <EventsDetailField :field-name="'Body:'" :field-data="event.bodyPreview | checkForEmpty"/>
    <EventsDetailField :field-name="'Organizer:'" :field-data="event.organizer.emailAddress.name"/>
    <EventsDetailField :field-name="'Attendees:'" :field-data="event.attendees | trimAttendees"/>
    <EventsDetailField :field-name="'Location:'" :field-data="event.location.displayName | checkForEmpty"/>
    <EventsDetailField :field-name="'Start:'" :field-data="event.start.dateTime | dateFormatter"/>
    <EventsDetailField :field-name="'End:'" :field-data="event.end.dateTime | dateFormatter"/>
  </div>
</template>

<script>
import EventsDetailField from "@/components/user_components/calendar/form/EventsDetailField";

export default {
  name: "EventsDetail",
  components: {EventsDetailField},
  props: {
    event: {
      type: Object,
      required: true
    }
  },
  filters: {
    trimAttendees: value => {
      if (value.length) {
        let attendees = [];
        for (let i = 0; i < value.length; i++) {
          attendees.push(value[i].emailAddress.name);
        }
        return attendees.join(", ");
      }
      return '-';
    }
  }
}
</script>

// react-calendar/src/components/calendar/modal/EventsDetail.jsx
import React from 'react';
import {Modal, Button, Container} from 'react-bootstrap';
import EventsDetailField from "./EventsDetailField";
import {checkForEmpty, dateFormatter, trimAttendees} from "../filters";

const EventsDetail = ({visible, setVisible, event}) => {
    const handleClose = () => setVisible(false);
    return (
        <>
            <Modal show={visible} onHide={handleClose}>
                <Modal.Header closeButton>
                    <Modal.Title>Event info</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Container>
                        <EventsDetailField text={'Subject:'} value={event.subject}/>
                        <EventsDetailField text={'Body:'} value={checkForEmpty(event.bodyPreview)}/>
                        <EventsDetailField text={'Organizer:'} value={event.organizer.emailAddress.name}/>
                        <EventsDetailField text={'Attendees:'} value={trimAttendees(event.attendees)}/>
                        <EventsDetailField text={'Location:'} value={checkForEmpty(event.location.displayName)}/>
                        <EventsDetailField text={'Start:'} value={dateFormatter(event.start.dateTime)}/>
                        <EventsDetailField text={'End:'} value={dateFormatter(event.end.dateTime)}/>
                    </Container>
                </Modal.Body>
                <Modal.Footer>
                    <Button variant="danger" onClick={handleClose}>Close</Button>
                </Modal.Footer>
            </Modal>
        </>
    );
};

export default EventsDetail;
